import { WorkflowItem, WorkflowEnrollment } from "@/types/automation";

export const initialWorkflows: WorkflowItem[] = [
  {
    id: "wf-1",
    name: "User Signup - DB",
    description: "Auto-enrolls new users signing up from the website into a welcome sequence.",
    status: "active",
    version: 1,
    triggerType: "realtime_lead",
    triggerConfig: {
      watchedSources: ["User signups"],
      allowReEnrollment: false,
    },
    nodes: [
      {
        id: "node-trigger",
        type: "trigger",
        position: { x: 250, y: 50 },
        data: {
          label: "When a new lead arrives",
          subtitle: "Auto-enrolls matching new leads.",
          status: "READY",
          nodeType: "trigger",
        },
      },
      {
        id: "node-wait-1",
        type: "wait",
        position: { x: 250, y: 190 },
        data: {
          label: "Wait",
          subtitle: "6 hours",
          status: "READY",
          nodeType: "wait",
          config: { delayHours: 6 },
        },
      },
      {
        id: "node-email-1",
        type: "send_email",
        position: { x: 250, y: 330 },
        data: {
          label: "Send email",
          subtitle: "Free Resources: 500+ Claude P...",
          status: "READY",
          nodeType: "send_email",
          config: {
            fromEmail: "noreply@theproductspace.in",
            fromName: "The Product Space",
            subject: "Free Resources: 500+ Claude Prompts Included",
            emailBody: "Hi {{name}},\n\nHere are your free resources to crack PM interviews...",
          },
        },
      },
      {
        id: "node-wait-2",
        type: "wait",
        position: { x: 250, y: 470 },
        data: {
          label: "Wait",
          subtitle: "26 hours",
          status: "READY",
          nodeType: "wait",
          config: { delayHours: 26 },
        },
      },
      {
        id: "node-email-2",
        type: "send_email",
        position: { x: 250, y: 610 },
        data: {
          label: "Send email",
          subtitle: "Ready to Crack Your AI Product M...",
          status: "READY",
          nodeType: "send_email",
          config: {
            fromEmail: "noreply@theproductspace.in",
            fromName: "The Product Space",
            subject: "Ready to Crack Your AI Product Manager Role?",
            emailBody: "Hi {{name}},\n\nJoin our upcoming cohort...",
          },
        },
      },
      {
        id: "node-exit",
        type: "exit",
        position: { x: 250, y: 750 },
        data: {
          label: "Exit",
          subtitle: "End of workflow",
          status: "READY",
          nodeType: "exit",
        },
      },
    ],
    edges: [
      { id: "e1", source: "node-trigger", target: "node-wait-1", type: "addStepEdge" },
      { id: "e2", source: "node-wait-1", target: "node-email-1", type: "addStepEdge" },
      { id: "e3", source: "node-email-1", target: "node-wait-2", type: "addStepEdge" },
      { id: "e4", source: "node-wait-2", target: "node-email-2", type: "addStepEdge" },
      { id: "e5", source: "node-email-2", target: "node-exit", type: "addStepEdge" },
    ],
    stats: {
      active: 346,
      completed: 389,
      failed: 0,
      cancelled: 16,
    },
    createdAt: "23 Jul 2026, 10:29 AM",
    updatedAt: "23 Jul 2026, 10:29 AM",
  },
  {
    id: "wf-2",
    name: "Resources - DB",
    description: "Triggers on resource download forms.",
    status: "active",
    version: 1,
    triggerType: "realtime_lead",
    nodes: [],
    edges: [],
    stats: { active: 19, completed: 142, failed: 0, cancelled: 2 },
    createdAt: "23 Jul 2026, 10:29 AM",
    updatedAt: "23 Jul 2026, 10:29 AM",
  },
  {
    id: "wf-3",
    name: "Meta Ads Workflow",
    description: "Lead ads auto-responder.",
    status: "active",
    version: 1,
    triggerType: "realtime_lead",
    nodes: [],
    edges: [],
    stats: { active: 178, completed: 890, failed: 1, cancelled: 5 },
    createdAt: "13 Jun 2026, 09:35 AM",
    updatedAt: "13 Jun 2026, 09:35 AM",
  },
  {
    id: "wf-4",
    name: "Ads Leads Automation",
    description: "Draft automation for advertising campaigns.",
    status: "draft",
    version: 1,
    triggerType: "static_list",
    nodes: [],
    edges: [],
    stats: { active: 0, completed: 0, failed: 0, cancelled: 0 },
    createdAt: "11 Jun 2026, 01:44 PM",
    updatedAt: "12 Jun 2026, 06:48 PM",
  },
  {
    id: "wf-5",
    name: "Website Enroll Now",
    description: "Website course enrollment workflow.",
    status: "paused",
    version: 1,
    triggerType: "realtime_lead",
    nodes: [],
    edges: [],
    stats: { active: 0, completed: 54, failed: 0, cancelled: 3 },
    createdAt: "29 May 2026, 03:58 PM",
    updatedAt: "29 May 2026, 04:26 PM",
  },
];

export const initialEnrollments: WorkflowEnrollment[] = [
  {
    id: "enr-1",
    workflowId: "wf-1",
    leadName: "Deborah",
    leadEmail: "okafordeborah570@gmail.com",
    source: "users 45093",
    status: "active",
    currentNodeId: "n_2umdd1",
    enrolledAt: "28 Jul 2026, 12:27 PM",
  },
  {
    id: "enr-2",
    workflowId: "wf-1",
    leadName: "Mahendra (23KN1A44A7)",
    leadEmail: "chowdarymahendra610@gmail.com",
    source: "users 45092",
    status: "active",
    currentNodeId: "n_2umdd1",
    enrolledAt: "28 Jul 2026, 12:20 PM",
  },
  {
    id: "enr-3",
    workflowId: "wf-1",
    leadName: "Lakshay Mathur",
    leadEmail: "lakshaymathur91@gmail.com",
    source: "users 45091",
    status: "active",
    currentNodeId: "n_2umdd1",
    enrolledAt: "28 Jul 2026, 12:18 PM",
  },
  {
    id: "enr-4",
    workflowId: "wf-1",
    leadName: "Akanksha Agrawal",
    leadEmail: "agrawal.akanksha137@gmail.com",
    source: "users 45090",
    status: "active",
    currentNodeId: "n_2umdd1",
    enrolledAt: "28 Jul 2026, 12:15 PM",
  },
  {
    id: "enr-5",
    workflowId: "wf-1",
    leadName: "Aglodiya Amin",
    leadEmail: "aglodiyaamin7561@gmail.com",
    source: "users 45089",
    status: "active",
    currentNodeId: "n_2umdd1",
    enrolledAt: "28 Jul 2026, 12:13 PM",
  },
  {
    id: "enr-6",
    workflowId: "wf-1",
    leadName: "ARNAB BHANJA DEO",
    leadEmail: "arnabasanshu8987@gmail.com",
    source: "users 45088",
    status: "active",
    currentNodeId: "n_2umdd1",
    enrolledAt: "28 Jul 2026, 12:10 PM",
  },
];
